version: '3.7'
services:
  mongo:
    image: mongo:3.6-jessie
    container_name: ${MONGO_HOST}
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    - APP_MONGO_HOST=${MONGO_HOST}
    - MONGO_PORT=${MONGO_PORT}
    - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
    - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
    - APP_MONGO_USER=${APP_MONGO_USER}
    - APP_MONGO_PASS=${APP_MONGO_PASS}
    - APP_MONGO_DB=${APP_MONGO_DB}
    volumes:
    - "/home/maxoumask/dev/crypto_testing_bed/docker/volumes/mongo/data:/data/db"
    - "/home/maxoumask/dev/crypto_testing_bed/docker/mongo/entrypoints/:/docker-entrypoint-initdb.d/"
    ports:
    - "${MONGO_PORT}:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
